### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by dhruvmanila** [dhruvmanila/dotfiles#15]
# ToDo

## Neovim

- [x] Configure LSP Codelens (62b0f58)
- [ ] Add description (`desc`) for all the commands and keymaps to display useful information.
- [ ] Add `digraphs` picker for Telescope (`:h digraph-table`) ([plugin](https://github.com/protex/better-digraphs.nvim))
- [x] Move to using autocmd API function
- [ ] Use `winbar` similar to VSCode?

### Language

- [x] Setup Go debugging through `dlv` in Neovim
- [x] Setup C debugging in Neovim
- [x] #16

### Update

- [x] hrsh7th/nvim-cmp@593a634 implement kind highlights ([Wiki](https://github.com/hrsh7th/nvim-cmp/wiki/Menu-Appearance#how-to-add-visual-studio-code-dark-theme-colors-to-the-menu))
- [ ] nvim-telescope/telescope.nvim@7cfddbf configure preview width in bottom pane layout
- [x] Use `.luarc.json` for configuring the `lua-language-server` for dotfiles
- [ ] Use [gh-markdown-preview](https://github.com/yusukebe/gh-markdown-preview) in [markdown.lua](https://github.com/dhruvmanila/dotfiles/blob/master/config/nvim/lua/dm/markdown.lua)
- [x] Update `log_autocmds.vim` to `lua` once the args PR merges in core (subscribed).

### Colorscheme

- [x] Use dark background for floating windows
- [ ] Maybe define all the colors as a table and loop through them?
- [x] Update to use `nvim_set_hl`
```lua
---@param from string
---@param to string
hl_default_link = function(from, to)
  vim.api.nvim_set_hl(0, from, { default = true, link = to })
end
```

### Plugins

- Could we integrate [nvim-workbench](https://github.com/marcushwz/nvim-workbench) in our workflow? I would write my own implementation.
- Alternate package manager
  - [`dep` - Neovim Package Manager](https://github.com/chiyadev/dep)
  - [`vim-jetpack`](https://github.com/tani/vim-jetpack)
- Preview folds in floating window: [pretty-fold.nvim](https://github.com/anuvyklack/pretty-fold.nvim)
- Editing the buffer edits the filesystem!: [dirbuf.nvim](https://github.com/elihunter173/dirbuf.nvim). Currently, this does not allow changes across directories.

## Zsh

- [x] #13 
- [x] Configure [Powerlevel10k](https://github.com/romkatv/powerlevel10k) prompt (2fc3ed3)
- [ ] Take a look at [`cdr` plugin](https://github.com/zsh-users/zsh/blob/master/Functions/Chpwd/cdr). Maybe it could replace `cdpath`?

**Comment by dhruvmanila** [comment]
Tracking in https://linear.app
