### ISSUE TITLE
Custom colorscheme setup

### ISSUE THREAD

**Issue by dhruvmanila** [dhruvmanila/dotfiles#5]
Define your own colorscheme as `gruvbox-material` takes around 25ms to load. 

Use gruvbox colors, obviously :)

 Some references to use:
 - `lush.nvim` - https://github.com/rktjmp/lush.nvim
 - `tokyonight.nvim` - https://github.com/folke/tokyonight.nvim
 - `gruvbox-material` - https://github.com/sainnhe/gruvbox-material
 - `gruvy.nvim` - https://github.com/elianiva/gruvy.nvim

---
### TODO:
- [x] Define the color palette
- [x] Define the default highlight groups (`:h highlight-default`)
- [x] Define the Neovim LSP highlight groups (`:h lsp-highlight`)
- [x] Define the `treesitter` [highlight groups](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/plugin/nvim-treesitter.vim)
- [x] Define the highlight groups for installed plugins (only override the ones whose default is not looking good):
  - [x] Telescope
  - [x] ~~NvimTree~~
  - [x] Lir
  - [x] Gitsigns
  - [x] Statusline
  - [x] Tabline

**Comment by dhruvmanila** [comment]
So, I've been thinking about how would we go about setting the highlights using native API functions and found this: https://github.com/fsouza/dotfiles/blob/main/nvim/lua/fsouza/color.lua. It is using the decoration provider to setup the highlight groups. The same API used by builtin tree-sitter highlighter to highlight the buffer. I also learned that tree-sitter highlights the buffer using extmarks!

References:
- https://github.com/fsouza/dotfiles/blob/main/nvim/lua/fsouza/color.lua - Logic for using `nvim_set_decoration_provider` and `nvim_set_hl`
- https://github.com/neovim/neovim/blob/master/runtime/lua/vim/treesitter/highlighter.lua - Using extmarks to highlight the buffer

I will be using the logic of setting the highlight groups using `nvim_set_hl`, although note that `:h nvim_set_decoration_provider` provides the following note. We are not performing any of the below tasks so I think it should be fine.
```
Note: doing anything other than setting extmarks is considered experimental.
Doing things like changing options are not expliticly forbidden, but is
likely to have unexpected consequences (such as 100% CPU consumption).
doing `vim.rpcnotify` should be OK, but `vim.rpcrequest` is quite dubious
for the moment.
```

**Comment by dhruvmanila** [comment]
UPDATE: talking about this on gitter, it seems that this should not be done
